server:
  port: 8089



logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR




spring:
  datasource:
    url: jdbc:h2:file:./h2/code-generator;
  h2:
    console:
      enabled: true



  jpa:
    hibernate:
      ddl-auto:

flyway:
  enabled: true
  baseline-on-migrate: true




